### ISSUE TITLE
게시판에서 관리자 메일 보내기 기능을 사용할 때 비회원이 글을 작성한다면

### ISSUE THREAD

**Issue by ForPeople** [kijin/xe-advanced-mailer#11]
우리메일에서 고객중에 한분이 제보해 주셨습니다.

![](https://woorimail.com:20080/files/attach/images/414/556/005/484858e76226ff665b8f19b9ca0b9bd9.jpg)

이와같은 오류가 발생합니다.

검색해 보면

/modules/advanced_mailer/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:
  347              $address)) {
  348              throw new Swift_RfcComplianceException(
  349:                 'Address in mailbox given ['.$address.
  350                  '] does not comply with RFC 2822, 3.6.2.'
  351                  );

1 match in 1 file

혹시 이것이 아닌가 싶습니다.

**Comment by ForPeople** [comment]
음.. 아마 최신 버전으로 안해서 그런것 같습니다.
제가 최신버전으로 해보니 에러가 안나는군요.

**Comment by kijin** [comment]
#7 과 똑같은 문제이고, 1.5 버전에서 해결되었습니다.

그러나 에러가 나지 않는다고 메일이 정상적으로 발송되고 있는 것은 아닙니다. 다른 모듈의 설정 오류 때문에 보낸이 또는 받는이의 메일 주소가 누락될 경우 저렇게 됩니다. 자세한 예는 #7 을 참고하세요.

1.5 버전에서 에러 기록 기능을 켜두면 에러가 발생할 때마다 보낸이, 받는이, 에러 메시지, 메일 발송을 시도한 모듈 정보가 기록됩니다. 문제의 모듈을 찾아서 해결하는 것이 가장 좋습니다.
