### ISSUE TITLE
SendGrid API를 사용할 수 없습니다

### ISSUE THREAD

**Issue by fromthere** [kijin/xe-advanced-mailer#12]
SendGrid API 설정을 마친 뒤 메일 테스트를 하면 아무런 일도 일어나지 않습니다.

**Comment by kijin** [comment]
제 서버에서는 SendGrid API가 잘 작동합니다. 사용하시는 서버 환경에 대해 조금 더 자세히 알려주시면 감사하겠습니다.

![untitled](https://cloud.githubusercontent.com/assets/164058/8892819/c5f19f0c-33aa-11e5-82b7-5097c4b1fc04.png)

스크린샷과 같이 브라우저의 개발자도구를 사용해서 테스트 순간 발생하는 네트워크 통신 내용을 캡쳐해 주시면 더욱 도움이 됩니다. (디버깅에 꼭 필요한 에러 메시지가 서버측 응답에 포함되어 있을 가능성이 높습니다.)

**Comment by fromthere** [comment]
![image](https://cloud.githubusercontent.com/assets/10338434/8981058/4ef79bec-36f0-11e5-9570-6b33d6820dce.png)
HTTP 500 오류가 발생합니다. 

[XE Server Environment 2015-07-30]

location : ko
package : XE
app : Apache/2.4.12 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 mod_fcgid/2.3.9
xe_version : 1.8.7
php : 5.6.9
db_type : mysql_innodb
use_rewrite : Y
use_db_session : N
use_ssl : always
phpext : core, ereg, libxml, openssl, sqlite3, zlib, bcmath, bz2, calendar, curl, enchant, fileinfo, ftp, gd, gettext, iconv, intl, mbstring, mcrypt, mysqlnd, mysql, phar, pspell, imap, simplexml, snmp, soap, sockets, exif, tidy, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, cgi-fcgi, suhosin, pdo_sqlite, pdo_mysql, memcache, sourceguardian, mysqli, ioncube loader, zend guard loader
module : adminlogging(1.7), ads(0.1), advanced_mailer(1.5), analytics(1.0.1), antiaccess(1.0.3.1), attendance(7.0.1), auto_login(1.1.4), beluxe(2.8.3), board(1.7.2), board_extend(1.1), chmodule(0.2), contact(1.7.0.2), copytrack(0.1.1), coupon(1.0), cphosting(0.1), elfinderxe(0.1), faq(1.7.0.1), forum(1.7.0.1), ggmailing(0.3.9), guestbook(1.7.0.1), ipguard(1.7.3.4), isx(1.7.4.1), krzip(1.8.0), loginlog(0.5.1), mail_m9(0.1), mailing_free(0.2.1), material(1.0), minimaster(0.1.0), multidomain(1.3.1), ncenterlite(2.1.4), plusad(0.5), pointsend(1.2.5.1), privilege(0.1.2), profiler(1.0), quiz(1.0), referer(3.8.2), resource(1.7.0), sejin7940_comment(1.5), seo(0.2.0), socialxe(1.8.2), speedlimiter(1.3.1), syndication(4.0), textyle(1.7.0), textylehub(1.7.0), timeline(1.0.2), upgletyle(0.1.4), upgletylehub(1.7.0), wiki(1.7.0.1), xewall(0.3.1), ximember(1.4), zzz_menu_new(1.7.0)
addon : 301moved(0.2), AntiProxy(1.0.0), Redirection(1.0), aa_insert_ad(1.0.0), aaa_insert_ad(1.0.0), activescrollbar(1.0), addon_linker(1.0), adminlogging(1.7), adult_keyword(1.0), auth_email(0.1), autolang(1.0), bootstrap3_css(1.0), bootstrap_btn(1.0), bootstrap_icon(1.0), bot_title_control(0.2), captcha_member(1.7), chwisoseon(0.0.1), css3pie_js(1.1.1), datauri(0.0.1), document_content_change(1.0), domain_check(0.2), download_wanna_reply(1.0), dragcolor(1.0), dsori_ckeditor_setting(0.1740.3), dyform_no_spam(0.4), elkha_simple_spam(0.1), fa_loader(4.2.0), fileicon(1.1), guest_name(1.1.2), hidden_module(0.3), html5audio_flash(1.5.1), ie6nomore(0.7), image_lazyload(0.3.1), ipguard_post(1.7.3.4), jquerycdn(1.0.3), kru_dab(1.1), kru_sslhelper(3.0.1), layerAlert(1.1), layerpopup(1.10), mcguard(0.3.5), member_control(0.1), member_join_ex(0.2.3), member_layer_config(1.1), meta_add(0.2.2), mresizer(1.5), multidomain(1.2), naver_analytics(1.2), naver_syndication(0.1), new_document_notify2(1.0.12), no_adblock(1.1.3), nprogress(0.1.1), oembed(1.0), pnbsp(0.2), popup(0.1), radarURL(1.2), referer(3.4.1), scmplayer(1.5), scrolltopcontrol(1.1.0), sejin7940_autotrash(1.1.1), session_shield(1.8), sns_card(1.1), socialxe_helper(1.0.6), soo_autolang(1.0.3), soo_feed_delay(0.1), soo_parking(0.3a), stoptrackback(0.3), sxe_ncenter_plus(0.2), url_shortener(0.3), webfont(1.1.3.1), wiki_extend(0.1), xdt_css(1.0), xesticky(0.1), xetrace(1.0.0), zipperupper(0.3)
layout : archeage(0.2.1), ast_retra(1.1), AST_Tias(1.1), bootstrap(1.0), bootstrap.layout(1.0), Chemistry_lite(1.0), daol_official(1.1), doorweb_v4(1.7), flat_series(1.0.22), ideation(0.1), Ikoo2(9.0.2), purexe(1.1), rest_bootstrap(1.0), rkt001(1.0.0), simple_intro(1.0), simplestrap(1.4.2), the_bootstrap(3.5.1.2), verti(0.1.0), webengine_white(1.2), xe_cafe_site(1.7.0), xe_cafe(1.7.0), xe_cafe_hub(1.7.0), xdt_pure(1.5), white_square_layout(1.3), xe_admin(1.0), xe_official(1.7), xe_official_2(0.1), xedition(1.9), xe_official_v2(1.0), def_old(1.0), b_black(1.0), nyak(0.1.0), Dynamic(3.0), The_Simple_Classic_Lite(1.1), lol(0.1.0), migix_main(1.1), migix_sub(1.1), forhanbi_1.7(0.1), smart(0.9.9), ezcert_season2(1.1), ink(0.1.0), xecenter(1.3.7), kung_kwang_kung_kwang(1.0), user_layout(1.7)
widget : ads_widget(0.1), archive_list(0.1), autoredirect(1.0), browserWidget(0.2), calendar(0.2), category(0.1), contentsmedia(0.7), counter_status(1.7), eh_img_slider(3.0), forhanbiIframe(0.1), ggboardmailing_widget(0.2), logged_members(0.1), login_sunoo(1.0), member_group(0.1), navigator(1.7.0), (), plusadWidget(0.6), point_status(0.1), qrcode_creator(0.1), rank_count(1.5), rss_reader(#7), simple_calendar(1.0), simple_clock(1.0), site_info(1.7.0), sitemap(0.1.0), sitemap_selectbox(0.1.0), socialxe_comment(1.0.8), socialxe_info(1.0.6), srchat(219.48), sys_status(3.1.1), tag_list(0.1), treasurej_popular(1.0.5), uchat(1.1.7)
widgetstyle : simple(1.7), sweetMobileWidgetStyle(1.7)
max_file_uploads : 20
post_max_size : 50M
memory_limit : 128M

**Comment by kijin** [comment]
500 오류가 발생하는 요청을 클릭한 후, 오른쪽의 Response 탭을 열면 서버에서 응답한 내용이 나옵니다. (브라우저에 따라 더블클릭이 필요하거나, Response body라고 할 수도 있습니다.) 만약 서버에서 응답한 내용이 없다면 서버의 에러 로그를 보면 에러 메시지를 확인할 수 있습니다.

**Comment by fromthere** [comment]
아마도 서버와 sendgrid서버간 통신 문제 같습니다.(sendgrid에서 제공하는 예제도 오류가 나네요...) 일단 이슈는 닫겠습니다.
