### ISSUE TITLE
예외 member_srl 설정 필요합니다.

### ISSUE THREAD

**Issue by qw5414** [kijin/xe-advanced-mailer#13]
일부 사이트 기능을 위해서 일부러 관리용으로 쓰는 회원의 경우 로그인하지 않더라도 휴먼계정에 들어가면 안됩니다.

(예를들어서 포인트팡팡을 알려주는 모듈에서 생성한 맴버같은것들요...)
![_081015_060455_am](https://cloud.githubusercontent.com/assets/4381756/9156950/c444a4d4-3f25-11e5-932e-b6b88b0d6cfb.jpg)

포인트팡팡모듈(애드온을 모듈화시켜서 계정생성도 용의하게 만들어놨었습니다...) 에서 맴버 추가한 계정이라던지..관리용으로 쓰일 예정은 삭제되거나 휴면계정으로 전환이 되지 않아야 합니다..(각각 매 로그인하지 않더라도요..)
혹시 이부분은 제외할 수 있는 옵션으로 제공되었으면 좋겠습니다.
(기왕이면 여러 계정을 쉽게 등록할 수 잇도록 해줬으면 좋겠어요..)
```Ex
101,102,103```
이런형태로요..

**Comment by kijin** [comment]
일단 `is_admin` = `Y`로 되어 있는 회원계정은 정리하지 않도록 되어 있습니다.

**Comment by qw5414** [comment]
@kijin 그렇지만, 해당 계정에 대해서는 관리자를 처리하고 잇지 않는 경우가 있어서요..
대부분 테스트 계정은 회원을 기준으로 작성되어야 하는 경우가 존재하기 때문에 관리자를 두지 않는경우도 있고요..

**Comment by qw5414** [comment]
헉 .. 휴면계정으로 이슈 남긴다는것이.. 여기에도 남겨버렸네요 ㅠ... 실수..하핫..ㅋㄷㅋㄷ
