### ISSUE TITLE
로그 삭제가 안되는 것 같습니다.

### ISSUE THREAD

**Issue by gosugoon** [kijin/xe-advanced-mailer#15]
발송/에러 로그 삭제가 안되는 것 같습니다.
라이믹스 최신 버전입니다. (개발자 버전아님)

**Comment by kijin** [comment]
XE용으로 배포한 고급메일발송모듈 1.8.1 버전인가요? 아니면 라이믹스에 내장된 버전인가요? 라이믹스 내장 버전이라면 라이믹스 쪽에 이슈를 남겨 주시기 바랍니다.

로그가 너무 많이 쌓여 있는 경우 삭제 도중 타임아웃에 걸릴 수도 있습니다.
