### ISSUE TITLE
받는이 도메인에 따라 발송 방법을 다르게 하는 옵션

### ISSUE THREAD

**Issue by kijin** [kijin/xe-advanced-mailer#4]
특히 한메일은 메일API에 따라 전혀 배달되지 않는 경우도 있음

받는이 도메인에 따라 세부적으로 설정할 수 있다면 가장 이상적이겠으나, 지나치게 복잡해질 우려가 있으므로 일부 국내 대형포털에 대한 옵션이라도 제공하면 좋겠음

이런 기능을 구현하려면 `send()` 메소드를 `Base` 클래스로 다시 불러들이고, `Base` 클래스에서 발송 방법에 알맞은 클래스를 별도로 호출하는 방식으로 리팩토링해야 함

**Comment by ForPeople** [comment]
우리메일은 한메일의 이상한 메일 수신 부분에 대한 대비가 되어 있습니다. 
우리메일은 릴레이 서버를 제공하는게 아니고 웹 기반으로 데이터를 받아서 자체적으로 가공해 전송하는 시스템이기 때문에 아무런 문제가 없습니다.
다만 한메일은 메일 수신자 누군가가 스팸 신고를 하는 순간 해당 메일서버 아이피를 블락하므로 이 부분은 메일서버가 제아무리 SPF 라던가 DKIM 을 가지고 있더라도 블락되어 버립니다.
이 경우 수동으로 한메일과 연락하여 아이피해제가 되어야 합니다.

**Comment by kijin** [comment]
그러니까 다른 포털로 보낼 때는 API를 사용하더라도 한메일로 보낼 때는 Gmail SMTP를 사용하는 등의 이중 설정이 필요할 수도 있죠. 유명 포털의 IP 대역을 함부로 막지는 못할 테니까요 ㅎㅎ

**Comment by ForPeople** [comment]
우리메일과 상관은 없지만 아예 이런 방법은 어떨까요?
어차피 SMTP 를 이용한다면 한메일 메일은 한메일 SMTP를 쓰는거지요 :)

**Comment by kijin** [comment]
음... 근데 한메일 하는 짓을 보면 자기네 IP를 덜컥 막아버릴지도 모른다는... ㅡ.ㅡ;;

**Comment by ForPeople** [comment]
SMTP들이 보면 일일 발송 제한이 있지 않을까요?
만약 그렇다면 그점도 공지가 되어야 할 것 같습니다.
제 기억으로 구글도 제한이 있었던것 같습니다.

**Comment by kijin** [comment]
하루 몇백 건 정도의 제한이 있죠. 그러나 그건 API들도 대부분 마찬가지이고, 시시때때로 바뀌는 정책을 일일이 파악해서 공지해 주기는 어렵기 때문에 사용자가 알아서 해야 할 부분으로 남겨둘까 합니다.

**Comment by kijin** [comment]
각 발송방법별 설정을 완전히 분리하도록 하여 (예: 우리메일과 Mailgun 모두 `api_key`라는 설정을 사용하지만, 두 가지 모두 설정하더라도 서로 덮어쓰지 않도록 조치) 나중에 여러 발송방법을 함께 사용할 수 있는 여지를 만들어 놓았습니다. 일단 이 정도쯤에서 배포하고, 좀더 자세히 설정하는 기능은 다음 버전에서 구현해 봐야겠네요.

**Comment by misol** [comment]
👍

**Comment by kijin** [comment]
예외 도메인 처리 기능이 완성되었으므로 이슈를 닫습니다.
곧 배포할 1.5 버전에 적용됩니다.
