### ISSUE TITLE
메일 발송 before 및 after 트리거 제공

### ISSUE THREAD

**Issue by kijin** [kijin/xe-advanced-mailer#5]
다른 모듈에서 메일 발송 전후에 다른 작업을 수행할 수 있도록 트리거를 제공할 필요가 있음

일단 `send()` 메소드 및 클래스 상속 구조를 개선해야 트리거 호출 시점을 한 군데로 통일할 수 있음

**Comment by ForPeople** [comment]
아 맞다. 이거 좋네요. 그동안 XE 자체적인 mail 클래스를 사용하고 있었던 사람들은 쓸데없이 코드를 많이 적어야 되고 일관성에서 부족한 부분이 있을수도 있었는데 mail 클래스를 통채로 제어하는 모듈이니까 트리거가.... 좋긴한데 이정도면 mail 클래스 관련 트리거는 코어에서 제공해야 하는것 아닐까요?

**Comment by kijin** [comment]
기회가 있으면 XE 프로젝트에 제안은 해 보겠지만, XE 1.x 버전대에서 더이상 그런 기능을 추가해 줄 거라고 기대되지는 않네요.

아무튼 트리거는 님처럼 메일과 관련된 다양한 기능을 개발하시는 분들의 편의를 위해서입니다 ^^

`$oMail` 오브젝트를 통째로 넘겨드릴 예정이므로, before에서는 메일 내용을 변경하거나 BCC를 추가하는 등의 작업이 가능하겠고, after에서는 메일 발송 내역을 DB에 저장하거나 발송에 실패한 경우 관리자에게 연락하는 등의 작업이 가능하겠습니다.

**Comment by ForPeople** [comment]
우리알림 모듈의 xe 메일 연동 옵션을 개선할 수 있을 것 같습니다.
