### ISSUE TITLE
전 왜 이런 에러가 날까요..

### ISSUE THREAD

**Issue by mactopia** [kijin/xe-advanced-mailer#6]
Parse error: syntax error, unexpected '[', expecting ')' in /host/home2/podoboy/html/modules/advanced_mailer/vendor/react/promise/src/functions.php on line 68

쩝.. 설치이후에 contact 모듈에서 보내봤습니다.

**Comment by kijin** [comment]
PHP 5.4 이상에서 사용하도록 만들어진 라이브러리를 PHP 5.3에서 호출하신 것 같습니다.

일부 발송방식은 PHP 5.4에서만 사용 가능하다고 공지해야겠네요.

혹시 Mailgun을 선택하셨나요? 아니면 다른 방식에서도 같은 문제가 발생하나요?

**Comment by mactopia** [comment]
아하..php 5.4 도 있었군요..죄송합니다. 저는 1.8.3 이상 이면 되는줄 알고...
그리고 선택한 방식은 php mail 이랑 smpt gmail 설정해서 테스트 해봤습니다.

**Comment by kijin** [comment]
공홈 자료실에 올릴 때 PHP 최소버전 조건을 지정할 수가 없네요 ㅠㅠ

일단 PHP 5.4 미만인 경우 자체적으로 설치를 막는 기능을 만드는 중입니다.

**Comment by mactopia** [comment]
네. 기진곰님 그래도 속시원합니다. ^^ 항상 감사 드립니다.

**Comment by ForPeople** [comment]
XE 최소 지원 버전이 php 5.3 임을 감안할때 조금 아쉬운 부분이 될 것 같습니다 :)

**Comment by bnu** [comment]
이 모듈의 문제는 아닙니다.
`composer install`을 하신 것 같은데, 이는 테스트 위한 vendor가 설치되는데 이것이 PHP 5.4 이상을 요구합니다.
필요하지 않다면 `vendor` 디렉토리를 지우면 사용 가능할겁니다.

**Comment by kijin** [comment]
해외 API 라이브러리는 의존성 관계가 복잡해서 일일이 분리하기가 힘들더군요. 각각 따로 관리하자니 composer를 사용하는 의미가 없어지고요.

일단 지금은 mailgun→guzzlehttp→react/promise 쪽에서만 PHP 5.4 문법을 사용하고 있는 것 같지만, 장기적으로는 다른 라이브러리들도 PHP 5.3과 호환성을 유지할 거라는 보장이 없습니다. 이미 5.3.3 이상을 요구하는 경우가 꽤 있기 때문에 5.3 계열을 모두 지원하는 것도 사실상 불가능하고요.

그래서 일단 치명적인 문법 오류를 막는 것이 가장 중요하다고 판단하고, 모듈 전체에 PHP 5.4 이상을 요구하기로 했습니다. 발송 방식에 따라 별도의 라이브러리가 필요하지 않은 경우에는 composer를 건너뛰고 꼭 필요한 클래스만 직접 인클루드하는 방식도 한번 고려해 보겠습니다. 왠지 석기시대로 돌아가는 듯한 느낌이 들긴 하지만요 ㅠㅠ

**Comment by kijin** [comment]
@bnu 공홈에 자료 올릴 때 PHP 최소 버전도 선언할 수 있도록 해주세요.

**Comment by kijin** [comment]
PHP 5.3에서도 `mail()` 함수, SMTP, 우리메일 API까지는 사용할 수 있도록 허락해 보았습니다.

PHP 5.3 서버를 사용하시는 분은 방금 커밋한 것으로 테스트해 주시면 감사하겠습니다.

**Comment by mactopia** [comment]
테스트 메일 을 해보니 아래 처럼 나오고요
Expected response code 250 but got code "535", with message "535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8 https://support.google.com/mail/answer/14257 pw7sm7540983pab.40 - gsmtp
"

실제 메일 계정에서는 누군가 로그인 시도가 있어 차단했다고 alert 메일이 옵니다. 물론 비밀번호 아이디는 여러번 확인했고요.

**Comment by kijin** [comment]
일단 모듈이 제대로 작동하긴 하나 보네요.

요즘 구글의 보안이 강화되어서, 낯선 IP에서 로그인하려고 하면 저렇게 거부당합니다. 구글 계정의 보안설정 페이지 맨 아래의 "Allow less secure apps" 옵션을 켜주면 된다고 들었는데, 이것도 항상 되는 건 아니라고 하네요.

**Comment by mactopia** [comment]
네. 그런것 같습니다. 구글 쪽으로 좀더 알아 보겠습니다.

**Comment by wookho** [comment]
보안 수준이 낮은 앱 허용: 사용 
Allow less secure apps

이게 계정 주인 스스로 설정하지 않으면 구글이 만들지 않은 앱이나 서비스에서 로그인을 시도시 차단당할거에요.

**Comment by kijin** [comment]
자체 테스트 결과 "보안 수준이 낮은 앱 허용"을 설정하면 몇 분 후부터 정상적으로 SMTP 이용이 가능한 것을 확인했습니다.

문제를 수정한 버전은 내일 배포할 예정입니다. 이 이슈는 닫겠습니다.
