### ISSUE TITLE
회원가입시 문제가 발생합니다.

### ISSUE THREAD

**Issue by wookho** [kijin/xe-advanced-mailer#7]
회원가입 등록을 누르면 

Address in mailbox given [] does not comply with RFC 2822, 3.6.2.

이런 메시지가 발생합니다. 이후 진행되어야 할 가입포인트 지급  그리고 회원가입확장모듈에서 가입회원에게 보내는쪽지 / 메일발송 이런 것들이 진행되지 않습니다.

그래서 가입한 회원들이 가입포인트가 없이 가입이 되었는데 이유를 모르다가 이 자료설치이후 인 점을 오늘 확이하고 해당 자료를 사용중지하며 비교해 보니 이 자료로 인해 위와 같은 메시지와 현상이 발생합니다.

해당모듈로 테스트메일은 잘 발송 수신 되는 것은 확인했습니다.

우리알림 API 를 이용하고 있습니다.

**Comment by kijin** [comment]
가입포인트 미지급이나 쪽지 발송 문제는 인증메일 발송이 되지 않아서 해당회원이 인증을 마치지 못했거나, 아니면 에러 때문에 메일 발송 이후의 코드들이 실행되지 못해서 일어나는 일 같습니다. 따라서 메일 발송 도중 에러가 나는 이유를 찾는 것이 가장 시급한 문제이겠는데요...

제 테스트 서버에서는 가입시 인증메일이 정상적으로 발송됩니다.

님이 언급하신 오류는 보낸이 또는 받는이의 메일 주소가 공백으로 들어가서 발생하는 오류입니다. 메일 주소가 잘못 들어간 정도가 아니라, 아예 공백으로 들어갔어요.

- 혹시 보낸이(웹마스터)의 메일 주소나 받는이의 메일 주소가 누락되었나요?
- 혹시 member 모듈의 실행에 영향을 미치는 다른 모듈을 사용하고 계시거나, member 모듈을 수정하고 쓰고 계신가요? 이 경우 방금 가입한 회원의 `$member_info->email_address` 정보가 공백으로 들어갈 여지가 있나요?
- 메일 발송 관련 코드가 아래의 예제와 조금이라도 다른 부분이 있나요?

    $oMail->setReceiptor( $member_info->user_name, $member_info->email_address );

아무튼 기존의 `Mail` 클래스를 사용하더라도 공백 메일주소로 인증메일 발송은 불가능해 보입니다. 단지 예외를 뿌려버리고 뻗느냐, 아니면 무시하고 그냥 넘어가느냐의 차이인 것 같은데요... 아무튼 기존 방식과의 차이점은 제가 좀더 알아보도록 하겠습니다.

**Comment by wookho** [comment]
아이고 내용이 좀 어렵네요. 가입된 회원들의 이메일은 모두 정상적인 이메일로 확인되어 지고 있구요. 모두 동일한 현상입니다. 

현제 코어에 우리메일을 사용하기 위한 수정은 되어 있는 상태입니다. 그대로 두어도 무방할 것 같아 그대로 둔 상태에서 모듈을 설치해서 사용중이었습니다.


모듈에서 테스트메일을 발송시 제대로 발송된 것이 확인되었고 우리알림에서 제공하는 게시판구독메일도 정상적으로 발송되고 있는 상황이었습니다.

**Comment by ForPeople** [comment]
오토로드라서 기존의 수정하신 메일 클라스 파일은 무시되는게 맞다면 
코어에서 우리메일을 위해 수정하신 내역은 문제가 안될것 같습니다.

**Comment by kijin** [comment]
기존의 수정내역이 `Mail.class.php`에 국한된다면 그건 상관없습니다.

이 모듈을 사용하지 않을 경우에는 가입인증 메일이 정상적으로 발송되는지 테스트 부탁드립니다.

**Comment by wookho** [comment]
네. @ForPeople 님께서 제공하신 수정방법 외에는 적용한게 없습니다.

**Comment by wookho** [comment]
@kijin 이 모듈을 사용하지 않으면 모든게 정상입니다. 메일발송도 잘 되고요 가입시 진행도 멈춤이 없습니다. 인증메일은 따로 발송하지 않고 있으나 가입환영메일은 발송하고 있습니다.

**Comment by ForPeople** [comment]
우리알림 모듈에서 XE코어 메일 클래스를 사용하는 기능 옵션은 Xe연동 옵션밖에 없습니다.
나머지 다른 게시판 메일링이라던가 하는 기능들은 모두 자체 cURL을 사용한 통신을 우리알림 모듈 내부에서 하고 있습니다.

**Comment by wookho** [comment]
아... .  지금 우리알림 사이트에서 메일전송내역 확인해 보니 기존에도 가입환영메일은 발송이 되지 않고 있었네요. 회원가입확장모듈에 메일발송으로 되어 있는데요.

모듈사용시 차이점은 가입이후 절차가 중단되는 현상인것 같습니다.

**Comment by ForPeople** [comment]
그건 아마 코어 업데이트로 인해 메일 클라스에 수정해놓은 코드 부분이 덮어 씌여서 그럴것 같습니다.

**Comment by kijin** [comment]
역시 그랬군요. 코어 자체에는 가입환영메일 발송 기능이 없거든요. 회원가입 확장모듈을 제가 한번 다운받아서 확인해 보겠습니다.

고급 메일 발송 모듈을 설치한 상태에서 가입환영 메일을 발송하지 않도록 설정하면 회원가입 및 가입포인트 지급이 정상적으로 이루어지는지 실험해 보실 수 있을까요?

**Comment by wookho** [comment]
@ForPeople 아니요. 체인지드로 업데이트 한거라 그동안 쭉 회원가입확장모듈의 가입환영메일은 무시되고 있었네요.

**Comment by wookho** [comment]
@kijin 네. 테스트해 보고 피드백 드릴게요.

**Comment by wookho** [comment]
@kijin 예상이 맞았습니다. 회원가입확장모듈의 가입환영메일 발송을 사용하지 않으니 나머지 절차가 진행이 잘 되서 가입환영 쪽지 / 가입포인트지급 모두 정상입니다.

회원가입확장모듈의 가입환영메일발송과 관련이있습니다.

**Comment by ForPeople** [comment]
메일 보내는 형식이 다른 모듈들과 차이가 있나 봅니다

**Comment by kijin** [comment]
회원가입 확장모듈의 소스를 확인해 보았습니다.

혹시 환영메일 발송자로 지정된 관리자 아이디가 유효한가요? 메일주소나 회원번호가 아닌 아이디(예: admin)여야 합니다. 그렇지 않을 경우 보낸이 메일 주소가 공백으로 들어갈 여지가 있어 보입니다.

상황을 정리하자면

- 회원가입 확장모듈의 버그 때문에 보낸이 메일 주소가 공백으로 들어갔는데
- 기존의 메일 클래스는 이런 경우 메일을 발송하지 않고 말았지만
- 고급 메일 발송 모듈은 에러를 내뿜어 버려서
- 환영메일 발송 이후의 단계들이 정상적으로 실행되지 않았습니다.

**Comment by wookho** [comment]
네. 상황은 그렇습니다. 

일단 해당 모듈의 문제는 아닌것으로 확인이 되어지네요.  이 회원가입 확장모듈이 오래된 것이라 예전에는 메일 발송이 잘 되었는데 최근에 안되는 것으로 추측이 되네요.

관리자 메일주소는 초기에 설정해 놓고 건드린 적이 없기에 이부분 오류는 없습니다.

**Comment by kijin** [comment]
아뇨, 관리자 메일주소 말고 회원가입 확장모듈의 이 설정 말씀드리는 겁니다.

![foobar](https://cloud.githubusercontent.com/assets/164058/8103042/4c6d66f6-1060-11e5-8e9d-d2962d46d356.png)

**Comment by wookho** [comment]
네. 거기는 오래전에 입력해 둔 그대로 입니다. 모듈 초기 사용시 관리자의 이메일로(저희는 이메일로그인사용) 설정해 놓은 상태입니다.

**Comment by kijin** [comment]
회원가입 확장모듈 소스를 분석해 보니, 관리자 이메일이 아닌 아이디를 넣어야 정상 작동하도록 되어 있습니다. 아이디를 일체 사용하지 않고 이메일로만 로그인한다면 방법이 없는 거죠. (DB를 직접 수정해서 관리자에게 강제로 아이디를 하나 지정해 준다면 모를까...)

**Comment by wookho** [comment]
@kijin 그런가요 ? 그런데 과거 가입환영 메일이 잘 갔다고 생각한데 한때 인증메일 사용할때를 착각했던 거 같네요. 그럼 db에 기록된 id를 찾아서 한번 넣어볼게요. 안되면 사용 못하는거죠. 다른 모듈 문제로 바쁘게 해드렸네요.

**Comment by wookho** [comment]
@kijin 아이고 모르고 있던 사실 하나 알려주셨네요. 아이디로 입력하니 잘 되네요. 감사합니다!

**Comment by kijin** [comment]
잘 해결되었다니 다행입니다. 덕분에 특정 모듈과의 호환성 문제에 대해 배웠네요 ^^

문제가 있을 경우 에러를 뿜고 뻗는 것이 옳은지, 아니면 무시하고 넘어가도록 하는 것이 옳은지는 좀더 생각해 봐야겠습니다. 기존 모듈과의 호환성을 표방한다면 다른 모듈들이 아무리 이상하게 동작하더라도 너그럽게 봐주는 것이 나을지도 모르겠어요. 그 대신, 문제가 있다는 것을 관리자가 파악할 수 있도록 해주는 것이 문제네요.

그럼 이 이슈는 닫겠습니다.
